config/routes.rb
Rails.application.routes.draw do
  # get 'stories/index'
  #
  # get 'stories/new'

   resources :stories
   root 'stories#index'

  
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, presence: true
  validates :writer, presence: true
  validates :preview, presence: true
  validates :url, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.page(params[:page]).per(25)
  end

  def new
    @story  = Story.new
  end

  def create
    @story = Story.new(params.require(:story).permit(:title, :writer, :preview, :url))
    if @story.save
      redirect_to root_path
    else
      render "new"
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Writersboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stories/index.html.erb
<h1>Stories</h1>

<% @stories.each do |story| %>
  <div class="story">
    <h2><%= link_to story.title, story.url %></h2>
    <p><%= story.preview %>
    <p><%= story.writer %>
  </div>
<% end %>

<p><%= paginate @stories %></p>

<p><%= link_to "Add a story", new_story_path %></p>

app/views/stories/new.html.erb
<%= simple_form_for @story do |form| %>
  <%= form.input :title, label: "Story Title" %>
  <%= form.input :writer, label: "Your name" %>
  <%= form.input :preview, label: "Your preview" %>
  <%= form.input :url, label: "Link to story" %>
  <%= form.button :submit %>
<% end %>